### ISSUE TITLE
SquareRoot0 XL line

### ISSUE THREAD

**Issue by agustin-del-pino** [CloudMracek/BandwidthPS1Game#1]
Hola,

I saw your video, super cool btw. And I can't let pass this loooong line:
```c
SquareRoot0(abs((pos.vx - enemies[j].pos.vx) * (pos.vx - enemies[j].pos.vx)) + abs((pos.vz - enemies[j].pos.vz) * (pos.vz - enemies[j].pos.vz)));
```

I don't know which compiler is used for compile to PSX, because depending on the compiler the stdlib implementation could change in sort kind. Also I dunno what the heck is SquareRoot0 (I sneaked in the SDK source code, but is fully assembly and exceed my knowledge), if you know and you want to explain me, would be really great!.

 So...
 1. `pos.vx - enemies[j].pos.vx` and  `pos.vz - enemies[j].pos.vz` -> can pass this to a variable for computes once. 
 
 2. You're requiring for the Absolute Value, as you already know the abs value is just the positive value of any Real Number, so you can use a Macro Function -> `#define ABS(N) (N < 0 ? -N : N)`. With this you avoid passing as argument and call to a function. Also, I think the implementation of `abs` function does the same thing (because is pure math logic description).
 
3. Referencing to the previous point, you already getting the abs value when you do the multiplication. That's because of the two factors will have the same sing (- * - = +) and (+ * + = +). So, if I understood correct, you don't need to calculate the abs value. In case I understood wrong, just use the MACRO 🙂.

4. (Optional). If you are lazy as me, use a MACRO for Cuadrado (no idea how to say it in english) -> `#define CRD(N) (N * N)`.

So the final image will be:

```c
#define ABS(N) (N < 0 ? -N : N)
#define CRD(N) (N * N)

int vx = (pos.vx - enemies[j].pos.vx);
int vz = (pos.vz - enemies[j].pos.vz);

SquareRoot0((CRD(vx))+(CRD(vz)));

```
 
[This is an executable example in C Playground](https://cpp.sh/?source=%2F%2F+Example+program%0A%23include+%3Ciostream%3E%0A%23include+%3Cstring%3E%0A%0A%23define+ABS(N)+(N+%3C+0+%3F+-N+%3A+N)%0A%23define+CRD(N)+(N+*+N)%0A%0A%2F%2F+Mock%0Aint+SquareRoot0(int+n)+%7B%0A++++return+n%3B%0A%7D%0A%0Atypedef+struct+%7B%0A++++int+vx%3B%0A++++int+vz%3B%0A++++%0A%7D+Position%3B%0A%0A%0Atypedef+struct+%7B%0A++++Position+pos%3B%0A%7D+Enemy%3B%0A%0A%0Aint+main()%0A%7B%0A++++Position+pos%3B%0A++++%0A++++pos.vx+%3D+10%3B%0A++++pos.vz+%3D+-45%3B%0A++++%0A++++%0A++++Enemy+e%3B%0A++++e.pos.vx+%3D+-342%3B%0A++++e.pos.vz+%3D+2%3B%0A++++%0A++++Enemy+enemies%5B1%5D+%3D+%7Be%7D%3B%0A++++%0A++++int+vx+%3D+(pos.vx+-+enemies%5B0%5D.pos.vx)%3B%0A++++int+vz+%3D+(pos.vz+-+enemies%5B0%5D.pos.vz)%3B%0A%0A++++%0A++++std%3A%3Acout+%3C%3C+SquareRoot0((CRD(vx))%2B(CRD(vz)))%3B%0A%7D%0A%0A%0A%0A)

I hope it help for the improvement of performance, I'm not a C dev so I can't guarantee.

Greetings from Argentina!. Super good job with this and the video, you got a new sub!.

**Comment by CloudMracek** [comment]
Thanks! I will definitely look into this during the next videos. This repo is more or less dead though...
